apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "headscale.fullname" . }}-post-install-job
  labels:
    {{- include "headscale.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      containers:
        - name: headscale-create-preauthkeys
          image: "{{ .Values.image.repository }}:{{ .Values.image.tagDebug }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["sh", "-c"]
          args:
            - |-
              echo "wait headscale ready"
              until nc -zv {{ include "headscale.fullname" . }}:{{ .Values.service.port }}; do
                sleep 2
              done
              headscale serve &
              until nc -zv 0.0.0.0:8080; do
                sleep 1
              done
              echo "create headscale user"
              headscale users create gorizond
              echo "create headscale token"
              token=`headscale preauthkeys create --user 1 --reusable --expiration 100y`
              echo -en "$token" > /tmp/token
          volumeMounts:
            - name: config
              mountPath: /etc/headscale
              readOnly: true
            - name: token
              mountPath: /tmp
        - name: secret-create-token
          image: bitnami/kubectl:latest
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c"]
          args:
            - |
              echo "wait /tmp/token"
              until [ -f /tmp/token ]; do
                sleep 2
              done
              kubectl create -n {{ .Release.Namespace }} secret generic "{{ include "headscale.fullname" . }}-token" --from-file=token=/tmp/token --dry-run=client -o yaml | kubectl apply -f -
          volumeMounts:
            - name: token
              mountPath: /tmp
      restartPolicy: OnFailure
      serviceAccount: "init-{{ include "headscale.fullname" . }}"
      serviceAccountName: "init-{{ include "headscale.fullname" . }}"
      volumes:
        - name: config
          secret:
            secretName: {{ include "headscale.fullname" . }}
        - emptyDir: {}
          name: token
