apiVersion: v1
kind: ServiceAccount
metadata:
  name: "init-{{ include "headscale.fullname" . }}"
  labels:
    {{- include "headscale.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "headscale.fullname" . }}-secret-manager
  labels:
    {{- include "headscale.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ''
    resources:
      - secrets
    verbs:
      - create
      - get
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "headscale.fullname" . }}-secret-manager-binding
  labels:
    {{- include "headscale.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "headscale.fullname" . }}-secret-manager
subjects:
  - kind: ServiceAccount
    name: "init-{{ include "headscale.fullname" . }}"
    namespace: {{ .Release.Namespace }}