apiVersion: v1
kind: Service
metadata:
  name: {{ include "headscale.fullname" . }}
  labels:
    {{- include "headscale.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - name: grpc
      port: 50444
      protocol: TCP
      targetPort: 50444
  selector:
    {{- include "headscale.selectorLabels" . | nindent 4 }}
